version: '3.9'
services:
  mongo:
    image: mongo:4.4.17-focal
    container_name: "mongo"
    restart: always
    ports: 
        - 27017:27017
    volumes: 
        - ./_data:/data/db
  webapi:
   image: ghcr.io/sing3demons/typescript-demo-api-22-10-2022/node-api-22-10-2022:0.0.1-snapshot
  #  build: .
   container_name: 'webapi'
   restart: always
   ports:
     - 3000:3000
   environment:
     - PORT=3000
     - MONGO_URI=mongodb://mongo:27017/test-api
     - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
     - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
     - FACEBOOK_APP_URL=http://localhost:3000/api/auth/login/facebook
     - SECRET_KEY=${SECRET_KEY}
     - GOOGLE_APP_ID=${GOOGLE_APP_ID}
     - GOOGLE_APP_SECRET=${GOOGLE_APP_SECRET}
     - GOOGLE_APP_URL=http://localhost:3000/api/auth/login/google
     - GMAIL=${GMAIL}
     - GMAIL_PASSWORD=${GMAIL_PASSWORD}
   volumes:
    - ./public:/public
   depends_on:
    - mongo